name: mongo-connectors

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      # - name: GitHub Action for Pytest
      # uses: cclauss/GitHub-Action-for-pytest@master
      # with:
      # args: pytest docker_django/hola_docker/*.py
    - name: Run AutoPEP8
      id: autopep8
      uses: peter-evans/autopep8@v1
      with:
        args: --recursive --in-place --aggressive --aggressive .
    - name: Build & Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: nicosistemas/mongoconnect
        tags: ${{ github.sha }}, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
